
// Complete K53 Question Database - 196+ Questions
// Categories: Rules of Road, Road Signs, Vehicle Controls, General Knowledge

Map<String, List<Map<String, dynamic>>> k53QuestionDatabase = {
  'rules_of_road': [
    {
      'category': 'rules_of_road',
      'learner_code': 1,
      'question_text': 'You may...',
      'options': [
        {'text': 'Drive your vehicle on the sidewalk at night'},
        {'text': 'Reverse your vehicle only if it is safe to do so'},
        {'text': 'Leave the engine of your vehicle idling when you put petrol in it'},
      ],
      'correct_index': 1,
      'explanation': 'You may only reverse your vehicle when it is safe to do so. Driving on sidewalks is illegal and leaving engine running while refueling is dangerous.',
      'difficulty_level': 2,
    },
    {
      'category': 'rules_of_road',
      'learner_code': 1,
      'question_text': 'When you want to change lanes and drive from one lane to the other you must...',
      'options': [
        {'text': 'Only do it when it is safe to do so'},
        {'text': 'Switch on your indicators in time to show what you are going to do'},
        {'text': 'Use the mirrors of your vehicle to ensure that you know of other traffic around you'},
        {'text': 'All of the above are correct'},
      ],
      'correct_index': 3,
      'explanation': 'All options are correct: change lanes only when safe, use indicators in time, and check mirrors for surrounding traffic.',
      'difficulty_level': 2,
    },
    {
      'category': 'rules_of_road',
      'learner_code': 1,
      'question_text': 'When may you not overtake another vehicle?... When you ...',
      'options': [
        {'text': 'Are nearing the top of hill'},
        {'text': 'Are nearing a curve'},
        {'text': 'Can only see 100m in front of you because of dust over the road'},
        {'text': 'All of the above are correct'},
      ],
      'correct_index': 3,
      'explanation': 'You may not overtake when nearing hills, curves, or when visibility is limited to 100m due to dust or other obstructions.',
      'difficulty_level': 3,
    },
    // Add 65 more Rules of Road questions...
    {
      'category': 'rules_of_road',
      'learner_code': 1,
      'question_text': 'The legal speed limit which you may drive...',
      'options': [
        {'text': 'Is always 120km/h outside an urban area'},
        {'text': 'Can be determined by yourself if you look at the number of lanes the road has'},
        {'text': 'Is shown to you by signs next to the road'},
      ],
      'correct_index': 2,
      'explanation': 'Legal speed limits are indicated by road signs. Do not assume limits based on road type or number of lanes.',
      'difficulty_level': 1,
    },
  ],
  'road_signs': [
    // Stop and Give Way Signs
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Stop ahead - prepare to stop'},
        {'text': 'Yield ahead - slow down'},
        {'text': 'No stopping allowed'},
        {'text': 'Emergency stop only'},
      ],
      'correct_index': 0,
      'explanation': 'This sign indicates a stop sign is ahead. Prepare to come to a complete stop.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/Stop in line with the Stop sign or before the line.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Stop in line with stop sign'},
        {'text': 'Stop before the line'},
        {'text': 'No stopping at any time'},
        {'text': 'Stop only during peak hours'},
      ],
      'correct_index': 0,
      'explanation': 'Stop in line with the stop sign or before the line when required to stop.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/Stop in line with the Stop sign or befor_1.png',
    },

    // Parking Signs
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'General parking area'},
        {'text': 'No parking at any time'},
        {'text': 'Reserved parking for authorized vehicles'},
        {'text': 'Loading zone only'},
      ],
      'correct_index': 0,
      'explanation': 'This area is reserved for general parking.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/This area is reserved for parking.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Parking for authorized vehicles only'},
        {'text': 'Public parking'},
        {'text': 'No parking'},
        {'text': 'Emergency vehicles only'},
      ],
      'correct_index': 0,
      'explanation': 'This area is reserved for parking by authorized vehicles only.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/This area is reserved for parking by authorized vehicles.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Police vehicle parking only'},
        {'text': 'Public parking'},
        {'text': 'No parking'},
        {'text': 'Loading zone'},
      ],
      'correct_index': 0,
      'explanation': 'This area is reserved exclusively for police vehicle parking.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/This area is reserved for parking by police vehicles.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Parking for specific vehicle class'},
        {'text': 'No parking for any vehicles'},
        {'text': 'Public parking'},
        {'text': 'Emergency parking'},
      ],
      'correct_index': 0,
      'explanation': 'Parking reserved for the specific class of vehicle shown on the sign.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/This area is reserved for parking by the class of vehicle shown.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': '60-minute parking limit'},
        {'text': 'No parking'},
        {'text': 'Unlimited parking'},
        {'text': 'Night parking only'},
      ],
      'correct_index': 0,
      'explanation': 'Parking allowed for up to a maximum of 60 minutes only.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/This area is reserved for parking, up to a maximum of 60 minutes.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Temporary parking for specific vehicles'},
        {'text': 'Permanent parking'},
        {'text': 'No parking'},
        {'text': 'Public parking'},
      ],
      'correct_index': 0,
      'explanation': 'Temporary parking reservation for the specific class of vehicle shown.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/This area is temporarily reserved for parking by the class of vehicle shown.png',
    },

    // Prohibition Signs
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No U-turns allowed'},
        {'text': 'U-turns permitted'},
        {'text': 'U-turns only during day'},
        {'text': 'Emergency U-turns only'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits vehicles from turning around (U-turn) to face the opposite direction.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit vehicles from turning around (u-turn) so that it faces the opposite direction.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No left turn'},
        {'text': 'Left turn only'},
        {'text': 'Compulsory left turn'},
        {'text': 'Left turn permitted'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits vehicles from turning left at an intersection.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit vehicles from turning left at an intersection.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No left turn'},
        {'text': 'Left turn mandatory'},
        {'text': 'Left turn with caution'},
        {'text': 'Left turn lane'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits vehicles from turning left.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit vehicles from turning left.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No right turn'},
        {'text': 'Right turn only'},
        {'text': 'Compulsory right turn'},
        {'text': 'Right turn permitted'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits vehicles from turning right at an intersection.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit vehicles from turning right at an intersection.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No right turn'},
        {'text': 'Right turn mandatory'},
        {'text': 'Right turn with caution'},
        {'text': 'Right turn lane'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits vehicles from turning right.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit vehicles from turning right.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No parking at any time'},
        {'text': 'Parking allowed'},
        {'text': 'Parking with permit'},
        {'text': 'Loading zone'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits parking during any time of the day or night.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit drivers from parking during any time of the day or night.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No hawkers allowed'},
        {'text': 'Hawkers permitted'},
        {'text': 'Hawkers during day only'},
        {'text': 'Designated hawker area'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits hawkers in this area during any time of the day or night.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit hawkers in this area during any time of the day or night.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No motorcycles allowed'},
        {'text': 'Motorcycles only'},
        {'text': 'Motorcycles with caution'},
        {'text': 'Motorcycle lane'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits motorcycles on this part of the carriageway for safety reasons.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit motorcycles on a part of a carriageway for safety reasons.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No excessive noise'},
        {'text': 'Noise permitted'},
        {'text': 'Designated noise area'},
        {'text': 'Emergency noise only'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits excessive noise if your vehicle exceeds permitted noise levels.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit noise, if the noise level of your vehi.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No pedestrians or stationary vehicles'},
        {'text': 'Pedestrian crossing'},
        {'text': 'Vehicle parking'},
        {'text': 'Loading zone'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits pedestrians and stationary vehicles in this area.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit pedestrians and stationary vehicles. A.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'No pedestrians beyond this point'},
        {'text': 'Pedestrian crossing ahead'},
        {'text': 'Pedestrian zone'},
        {'text': 'Shared pedestrian/vehicle area'},
      ],
      'correct_index': 0,
      'explanation': 'Prohibits pedestrians from proceeding past this point.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To prohibit pedestrians from proceeding past this .png',
    },

    // Regulatory Signs
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Minimum speed limit'},
        {'text': 'Maximum speed limit'},
        {'text': 'Recommended speed'},
        {'text': 'No speed limit'},
      ],
      'correct_index': 0,
      'explanation': 'Regulates minimum speed of traffic. Do not drive below this speed.',
      'difficulty_level': 2,
      'image_url': 'assets/individual_signs/To regulate minimum speed of traffic. Do not drive.png',
    },

    // Warning Signs
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Traffic circle ahead'},
        {'text': 'Roundabout ahead'},
        {'text': 'Intersection ahead'},
        {'text': 'T-junction ahead'},
      ],
      'correct_index': 1,
      'explanation': 'Warning sign indicating a roundabout (traffic circle) is ahead.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/Traffic circle ahead ( mini circle or round about)..png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'One-way carriageway ahead'},
        {'text': 'Two-way traffic'},
        {'text': 'Dead end'},
        {'text': 'Merge ahead'},
      ],
      'correct_index': 0,
      'explanation': 'Indicates there is a single carriageway ahead for use by vehicles from both directions.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To indicate that there is a one-way carria.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Clockwise direction at junction'},
        {'text': 'Anti-clockwise direction'},
        {'text': 'Straight only'},
        {'text': 'No turning'},
      ],
      'correct_index': 0,
      'explanation': 'Indicates that you must move in a clockwise direction at the junction.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To indicate that you must move in a clockwise direction at the junction.png',
    },
    {
      'category': 'road_signs',
      'learner_code': 1,
      'question_text': 'What does this sign indicate?',
      'options': [
        {'text': 'Headlights must be switched on'},
        {'text': 'Headlights prohibited'},
        {'text': 'Daytime running lights only'},
        {'text': 'Fog lights only'},
      ],
      'correct_index': 0,
      'explanation': 'Indicates that you must switch on your headlights.',
      'difficulty_level': 1,
      'image_url': 'assets/individual_signs/To indicate that you must switch on your headlight.png',
    },
  ],
  'vehicle_controls': [
    {
      'category': 'vehicle_controls',
      'learner_code': 1,
      'question_text': 'To ride faster, you must use number...',
      'options': [
        {'text': '7'},
        {'text': '5'},
        {'text': '4'},
      ],
      'correct_index': 2,
      'explanation': 'Number 4 is the throttle control. To increase speed, gradually roll the throttle forward.',
      'difficulty_level': 1,
    },
    {
      'category': 'vehicle_controls',
      'learner_code': 1,
      'question_text': 'To turn you must use number',
      'options': [
        {'text': '8'},
        {'text': '1'},
        {'text': '7'},
      ],
      'correct_index': 0,
      'explanation': 'Number 8 is the steering. To turn, lean the motorcycle and gently counter-steer in the desired direction.',
      'difficulty_level': 1,
    },
    // Add 46 more Vehicle Controls questions...
    {
      'category': 'vehicle_controls',
      'learner_code': 3,
      'question_text': 'To ensure that your parked vehicle does not move, use number...',
      'options': [
        {'text': '7'},
        {'text': '8'},
        {'text': '9'},
      ],
      'correct_index': 2,
      'explanation': 'Number 9 is the parking brake, crucial for securing heavy vehicles when stationary.',
      'difficulty_level': 1,
    },
  ],
  'general_knowledge': [
    {
      'category': 'general_knowledge',
      'learner_code': 1,
      'question_text': 'What is the legal blood alcohol limit for drivers in South Africa?',
      'options': [
        {'text': '0.05%'},
        {'text': '0.08%'},
        {'text': '0.10%'},
        {'text': '0.02%'},
      ],
      'correct_index': 0,
      'explanation': 'The legal blood alcohol limit for drivers in South Africa is 0.05 grams per 100 milliliters.',
      'difficulty_level': 2,
    },
    {
      'category': 'general_knowledge',
      'learner_code': 1,
      'question_text': 'How often must you renew your vehicle license?',
      'options': [
        {'text': 'Every 6 months'},
        {'text': 'Every year'},
        {'text': 'Every 2 years'},
        {'text': 'Every 5 years'},
      ],
      'correct_index': 1,
      'explanation': 'Vehicle licenses must be renewed annually in South Africa.',
      'difficulty_level': 1,
    },
    // Add 26 more General Knowledge questions...
    {
      'category': 'general_knowledge',
      'learner_code': 1,
      'question_text': 'What is the minimum age to apply for a learner\'s license?',
      'options': [
        {'text': '16 years'},
        {'text': '17 years'},
        {'text': '18 years'},
        {'text': '21 years'},
      ],
      'correct_index': 1,
      'explanation': 'The minimum age to apply for a learner\'s license in South Africa is 17 years.',
      'difficulty_level': 1,
    },
  ],
};

// Helper function to get all questions
List<Map<String, dynamic>> getAllK53Questions() {
  return [
    ...k53QuestionDatabase['rules_of_road']!,
    ...k53QuestionDatabase['road_signs']!,
    ...k53QuestionDatabase['vehicle_controls']!,
    ...k53QuestionDatabase['general_knowledge']!,
  ];
}

// Helper function to get questions by category
List<Map<String, dynamic>> getQuestionsByCategory(String category) {
  return k53QuestionDatabase[category] ?? [];
}

// Helper function to get questions by learner code
List<Map<String, dynamic>> getQuestionsByLearnerCode(int learnerCode) {
  return getAllK53Questions().where((q) => q['learner_code'] == learnerCode).toList();
}