-- Road Sign Specific Questions for K53 Test
-- Generated by scripts/seed_road_sign_questions.dart
-- These questions focus specifically on road sign recognition and interpretation
-- Uses only descriptive image names (avoids sign_page_ prefixed images)

INSERT INTO questions (id, category, learner_code, question_text, options, correct_index, explanation, version, is_active, difficulty_level, image_url, created_at, updated_at)
SELECT 
  gen_random_uuid(),
  data.category,
  data.learner_code,
  data.question_text,
  data.options,
  data.correct_index,
  data.explanation,
  1,
  true,
  data.difficulty_level,
  data.image_url,
  NOW(),
  NOW()
FROM (
  VALUES
    ('regulatory', 1, 'What does this sign indicate?', '[{"text": "Maximum speed limit allowed"},{"text": "Minimum speed requirement"},{"text": "Recommended speed"}]'::jsonb, 0, 'This circular sign with red border indicates the maximum speed limit allowed on this road section.', 1, 'assets/individual_signs/Maximum speed limit allowed.png'),
    ('regulatory', 1, 'This sign prohibits:', '[{"text": "No stopping to ensure traffic flow"},{"text": "No parking allowed"},{"text": "Loading zone only"}]'::jsonb, 0, 'The no stopping sign prohibits any stopping to maintain traffic flow and prevent disruptions.', 1, 'assets/individual_signs/No stopping to ensure traffic flow and prevent dri.png'),
    ('regulatory', 1, 'This parking sign indicates:', '[{"text": "Paid parking only"},{"text": "Free parking available"},{"text": "No parking at any time"}]'::jsonb, 0, 'The parking fee sign shows that parking is only permitted if the parking fee is paid.', 1, 'assets/individual_signs/Parking only if you pay the parking fee.png'),
    ('regulatory', 1, 'What does this parking restriction sign specify?', '[{"text": "30-minute parking limit on weekdays 09-16, Saturday 08-13"},{"text": "No parking during these times"},{"text": "Free parking during these hours"}]'::jsonb, 0, 'Time-restricted parking signs specify the maximum parking duration and applicable time periods.', 2, 'assets/individual_signs/Parking_30min_Week_09-16_Sat_08-13.png.png'),
    ('regulatory', 1, 'This reserved parking is for:', '[{"text": "Vehicles carrying people with disabilities"},{"text": "Emergency vehicles only"},{"text": "Official government vehicles"}]'::jsonb, 0, 'Disabled parking signs reserve spaces specifically for vehicles transporting people with disabilities.', 1, 'assets/individual_signs/Parking here is reserved for a vehicle carrying people with disabilities.png'),
    ('prohibition', 1, 'This sign means:', '[{"text": "Overtaking prohibited for 500m"},{"text": "No U-turns allowed"},{"text": "No right turns"}]'::jsonb, 0, 'General overtaking prohibition signs ban all overtaking maneuvers for the specified distance.', 1, 'assets/individual_signs/Over taking vehicles is prohibited for the next 500m.png'),
    ('prohibition', 1, 'This sign prohibits:', '[{"text": "Overtaking for the next 2km"},{"text": "Stopping for any reason"},{"text": "Turning right"}]'::jsonb, 0, 'The overtaking prohibition sign with distance indication bans overtaking for the specified distance.', 1, 'assets/individual_signs/Overtaking prohibited for the next 2km.png'),
    ('prohibition', 1, 'What restriction does this sign impose on goods vehicles?', '[{"text": "No overtaking for 500m"},{"text": "Speed limit of 50km/h"},{"text": "No entry for goods vehicles"}]'::jsonb, 0, 'This specific prohibition applies only to goods vehicles regarding overtaking for the specified distance.', 2, 'assets/individual_signs/No over taking vehicles by goods vehicles for the next 500m.png'),
    ('prohibition', 1, 'What does this sign prohibit?', '[{"text": "No vehicles may enter this road"},{"text": "No heavy vehicles allowed"},{"text": "No pedestrians allowed"}]'::jsonb, 0, 'The no entry sign completely prohibits any vehicles from entering the road from this direction.', 1, 'assets/individual_signs/No vehicles may enter this road at any time.png'),
    ('prohibition', 1, 'This sign applies:', '[{"text": "Only to mini-buses"},{"text": "To all vehicles"},{"text": "Only to trucks"}]'::jsonb, 0, 'Signs with specific vehicle type restrictions apply only to the indicated vehicle category.', 2, 'assets/individual_signs/Applies only to mini-buses.png'),
    ('command', 1, 'When you see this sign, you must:', '[{"text": "Come to a complete halt"},{"text": "Slow down and proceed"},{"text": "Sound your horn"}]'::jsonb, 0, 'Stop signs require a complete halt at the stop line or before entering the intersection.', 1, 'assets/individual_signs/Come to a complete halt in line with the stop sign.png'),
    ('command', 1, 'This sign indicates you must:', '[{"text": "Move in a clockwise direction"},{"text": "Turn right only"},{"text": "Make a U-turn"}]'::jsonb, 0, 'Circular direction signs mandate the direction of travel around traffic circles or roundabouts.', 2, 'assets/individual_signs/To indicate that you must move in a clockwise direction at the junction.png'),
    ('command', 1, 'What action must you take when you see this sign?', '[{"text": "Yield to other traffic"},{"text": "Stop completely"},{"text": "Proceed with caution"}]'::jsonb, 0, 'The yield sign (inverted triangle) requires you to give way to other vehicles on the major road.', 1, 'assets/individual_signs/Indicates that you must yield to other traffic. Gi.png'),
    ('warning', 1, 'This sign warns of:', '[{"text": "Traffic circle ahead"},{"text": "Sharp curve ahead"},{"text": "Pedestrian crossing"}]'::jsonb, 0, 'Roundabout warning signs alert drivers to an upcoming traffic circle requiring reduced speed and caution.', 1, 'assets/individual_signs/Traffic circle ahead ( mini circle or round about)..png'),
    ('warning', 1, 'What should you do when you see this sign?', '[{"text": "Give way to pedestrians"},{"text": "Increase speed"},{"text": "Change lanes"}]'::jsonb, 0, 'Pedestrian warning signs indicate areas where pedestrians may be crossing and require extra caution.', 1, 'assets/individual_signs/Give way to any pedestrians on or about to enter t.png'),
    ('freeway', 1, 'This sign indicates:', '[{"text": "Dual-carriage freeway begins"},{"text": "Freeway ends ahead"},{"text": "Toll road ahead"}]'::jsonb, 0, 'Freeway beginning signs mark the start of freeway sections where specific freeway rules apply.', 2, 'assets/individual_signs/Dual-carriage freeway begins The following rules apply to all freeways.png'),
    ('freeway', 1, 'When you see this sign:', '[{"text": "Freeway rules no longer apply"},{"text": "Freeway begins ahead"},{"text": "Toll payment required"}]'::jsonb, 0, 'Freeway end signs indicate that you are leaving the freeway and standard road rules resume.', 2, 'assets/individual_signs/End of dual carriage freeway and freeway rules no longer apply.png'),
    ('informational', 1, 'Entering this area means:', '[{"text": "Residential area rules apply"},{"text": "Commercial zone begins"},{"text": "Industrial area ahead"}]'::jsonb, 0, 'The residential area sign indicates that special rules for residential zones now apply, including lower speed limits.', 1, 'assets/individual_signs/Residential area.png'),
    ('mass_dimension', 1, 'This sign indicates the maximum allowed:', '[{"text": "Gross vehicle mass"},{"text": "Vehicle height"},{"text": "Vehicle width"}]'::jsonb, 0, 'Gross vehicle mass signs specify the maximum total weight allowed for vehicles on this road.', 2, 'assets/individual_signs/Gross vehicle mass limit allowed.png')
) AS data(category, learner_code, question_text, options, correct_index, explanation, difficulty_level, image_url);

-- Verify the insertions
SELECT 'Successfully inserted ' || COUNT(*) || ' road sign questions' AS result FROM questions WHERE category IN ('regulatory', 'prohibition', 'command', 'warning', 'freeway', 'informational', 'mass_dimension') AND created_at > NOW() - INTERVAL '1 minute';
